def mydesign1():
    d = turtle.Pen()
    d.screen.bgcolor("cyan")
    d.color("black")
    d.right(-45)
    d.forward(200)
    d.right(90)
    d.forward(100)
    d.right(90)
    d.forward(100)
    d.right(90)
    d.forward(200)
    d.right(-90)
    d.forward(100)
    d.right(-90)
    d.forward(100)

def mydesign2():
    d = turtle.Pen()
    d.screen.bgcolor("cyan")
    d.color("black")
    d.forward(150)
    d.left(120)
    d.forward(150)
    d.left(120)
    d.forward(150)
    d.left(150)
    d.forward(90)
    d.right(60)
    d.forward(90)

def mydesign3():
    d = turtle.Pen()
    d.screen.bgcolor("cyan")
    d.color("black")
    for i in range(4):
        d.forward(50)
        d.left(90)
    d.penup()
    d.setposition(-100,100)
    d.pendown()
    for i in range(4):
        d.forward(50)
        d.left(90)
    d.left(45)
    d.setposition(0,0)
    d.penup()
    d.left(45)
    d.setposition(50,0)
    d.pendown()
    d.setposition(-50,100)
    d.penup()
    d.left(45)
    d.setposition(-50,150)
    d.pendown()
    d.setposition(50,50)
    d.penup()
    d.left(45)
    d.setposition(0,50)
    d.pendown()
    d.setposition(-100,150)

def mydesign4():
    d = turtle.Pen()
    d.screen.bgcolor("cyan")
    d.color("black")
    d.circle(30)
    d.penup()
    d.setposition(200,0)
    d.pendown()
    d.penup()
    d.setposition(80,0)
    d.pendown()
    d.circle(30)
    d.penup()
    d.setposition(160,0)
    d.pendown()
    d.circle(30)
    d.penup()
    d.setposition(40,-30)
    d.pendown()
    d.circle(3)
